services:
  post-service:
    build: .
    container_name: post-service-api
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@post-db:5432/${DB_NAME}
      PORT: 3001
      S3_ENDPOINT: ${S3_ENDPOINT}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - post-db
      - minio
      - redis
    command: pnpm start:api

  post-worker:
    build: .
    container_name: post-service-worker
    restart: always
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@post-db:5432/${DB_NAME}
      S3_ENDPOINT: ${S3_ENDPOINT}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - post-db
      - minio
      - redis
    command: pnpm start:worker

  post-db:
    image: postgres:18-alpine
    container_name: post-service-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - post-db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: post-service-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  redis:
    image: redis:8-alpine
    container_name: post-service-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  post-db-data:
  minio-data:
  redis-data: