services:
  user-service:
    build: .
    container_name: user-service-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@user-db:5432/${DB_NAME}
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - user-db
    volumes:
      - ./src:/app/src

  user-db:
    image: postgres:18-alpine
    container_name: user-service-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

volumes:
  user-db-data: